### PR TITLE
Maintain Repo Proposal

### PR DESCRIPTION
**Pull request by AmanKumarSinhaGitHub**
Hello Hitesh Sir! 👋

I'm excited to step up my contribution level and offer my assistance in maintaining your GitHub repositories. You can find my profile at [AmanKumarSinhaGitHub](https://github.com/AmanKumarSinhaGitHub).

🚀 I'm deeply committed to contributing to open source, and I believe that my skills and dedication can be a valuable asset to your projects. Let's collaborate and make a meaningful impact together! 

Feel free to reach out to me if you have any questions or if there's anything specific you'd like to discuss.

You can also connect with me on [LinkedIn](https://www.linkedin.com/in/amankumarsinha/) or reach me via email at amankrsinha07@gmail.com.

Looking forward to working together! 🙏

Best regards,
Aman Kumar Sinha

### CODE REVIEW

**Comment by flyingcakes85** [comment]
image

**Comment by anuragts** [comment]
tf lmao

**Comment by flyingcakes85** [comment]
Dude just deleted his source repo :(

**Comment by anuragts** [comment]
are bhai merge to ho janne deta

**Comment by flyingcakes85** [comment]
I was waiting for the inter galactic repo cleanup 😞😞😞

**Pull request closed without merging**
