### PR TITLE
Adding chai-infused magic to the codebase ☕💻

### PR DESCRIPTION
**Pull request by pijushghorai**
Just spiced up the code with some chai-inspired magic! Hopefully, it'll add a dash of flavor to our project. If not, blame it on the tea leaves!🙂

### CODE REVIEW

**Review by flyingcakes85 — APPROVED** [review]
image

**Review by Solynhoo — APPROVED** [review]
nice

**Review by Solynhoo — APPROVED** [review]
open source contribuitor

**Comment by flyingcakes85** [comment]
image

**Comment by Solynhoo** [comment]
Me for real

**Pull request closed without merging**
