### PR TITLE
ds using c

### PR DESCRIPTION
**Pull request by rahulsrajput**
ds using c
open source contributor

### CODE REVIEW

**Review by flyingcakes85 — APPROVED** [review]
DSA in C is so much deja vu for me.

Approved!

**Review by flyingcakes85 — APPROVED** [review]
Approved.

**Review by flyingcakes85 — APPROVED** [review]
image

**Comment by rahulsrajput** [comment]
> Approved.

bhai visible q ni hai mera contribution open-source-contribution repo mai ??

**Comment by flyingcakes85** [comment]
Hitesh sir merge karenge tab hi visible hoga :)

**Comment by flyingcakes85** [comment]
@hiteshchoudhary sir merge kar dijiye :place_of_worship:

**Comment by rahulsrajput** [comment]
> Hitesh sir merge karenge tab hi visible hoga :)

okay first time contribution kar raha islye pucha 
thanks..

**Comment by flyingcakes85** [comment]
> > Hitesh sir merge karenge tab hi visible hoga :)
> 
> okay first time contribution kar raha islye pucha thanks..

Achha, toh thoda explain kar deta hu :wink: 

You create pull request to a repository. Then anyone can review it (remember, its open source!). So, (just for fun), I added a review on your merge request.

But it will be visible on the repository only when the it is merged. Only maintainers can merge. Eg.
- Repository owner (in this case, Hitesh sir)
- any other member given permissions on repo by repository owner

Once it is merged, it shows up on the repository.

**Comment by SharanIrani** [comment]
😂😂

**Comment by SharanIrani** [comment]
sad

> image

lol

**Pull request closed without merging**
