### PR TITLE
UpDaTiNg ReAdMe.Md

### PR DESCRIPTION
**Pull request by AnAverageBeing**
Plz Merg SAAR I Want JOOOB Saar I will Put it IN my CV SAAARRRR!!!

### CODE REVIEW

**Review by flyingcakes85 — COMMENTED** [review]
Lol you really did commit mp4 files :rofl:

**Comment by AnAverageBeing** [comment]
> Lol you really did commit mp4 files 🤣

Yes its all so funny idk how ppl get the idea that doing Open Source gets them a job but whatever its all very funny and i like meme driven development

**Comment by flyingcakes85** [comment]
> > Lol you really did commit mp4 files 🤣
> 
> Yes its all so funny idk how ppl get the idea that doing Open Source gets them a job but whatever its all very funny and i like meme driven development

Dude yeah people thinking OSS gets them a job is such cringe :/

I tried OSS during mid 2018. Reason? Because I thought the Linux distro I was using at the time was sick and I could contribute. It used to be about collaboration back then. More about discussing than competing.

Had conducted some seminars and literally every student asked me about job prospects :facepalm:

**Comment by AnAverageBeing** [comment]
> Had conducted some seminars and literally every student asked me about job prospects 🤦

This really sucks our(indian) education system is raising employees like we kill creativity and interest of students and all they can think of is money and getting a job like i really hate this i like to teach new ppl how to code and i also love linux so i teach them linux i like that when ppl are realy interested in coding but no all ppl want is money like i am in 12th and i really really like computers so i want to pursue career in computer science but here comes jee cs is hardest branch to get because its a high paying field and ppl over saturated it Like i cant even get good cse clg and in our education system all care about is that one final result like marks/score like man get real also idk why still cs dont have different entrance exam why should my chemistry and physics marks decide if i can do CS or not like what also most ppl are dumb like when they ask about computer they are all bout jobs and money in it like very less ppl are actually interested in the subject itself and in clg they study nothing at end they wanna get job so they see these bhaiya didi on yt teaching them coding (they themself are very at it) and promise them job so what students do they do this. Its all a bad system someone has to fix it in entrance exam filed there are these coaching taking unreal amount now in cs filed there are these bhaiya didi and big online ed tech ppl on yt teaching. Like ppl think they can just mug up and learn how to code like they did in their schools with studies like idk i can keep writing about this but its all so bad i really hate this

**Comment by AnAverageBeing** [comment]
> I tried OSS during mid 2018. Reason? Because I thought the Linux distro I was using at the time was sick and I could contribute. It used to be about collaboration back then. More about discussing than competing.

I myself did not know nothing about OSS all i wanted to do was write code and share it and store it so i was using github as storage lol but then by time i learned that ohh its actually something useful and now i put all my project and code for free online i made alternate to many paid tools and posted them for free and ppl liked it and i like to help ppl thats all i think like who cares about job and puting ur github and showing u made OSS contib. to get a job like cringe af.

**Comment by AnAverageBeing** [comment]
> Because I thought the Linux distro I was using at the time was sick and I could contribute

I also love linux i wanna contribute but i never feel confident enuf i always end up thinking my coding skills are not up the point. Like i am scared that i will write bad code to some popular project and it might end up causing problem later like ik ppl can make mistakes but still i always end up overthinking it but now i see this ppl doing bad spam pr now i think atlest i can do better than those ppl so i am thinking of contributing to hyprland codebase cuz the main creator is kinda tired like burn outs so he wants ppl help and i use hyprland sometimes and i really like it so i think i will help with that

**Comment by flyingcakes85** [comment]
> I also love linux i wanna contribute but i never feel confident enuf i always end up thinking my coding skills are not up the point.

man, if you can install Arch and learn Rust, you're already eligible for all sort of software dev :sunglasses: 


image


Also, when it comes to linux distros, there's a LOT (**LOT**) of non coding or low code work you can do (thats how I started). Some ideas for you
- maintain packages for the distro (this was my first try in 2019; though I failed because the build system for the distro I used at the time wasn't very intuitive. Later I maintained packages for EndeavourOS)
- maintain simple scripts to automate basic things
- make custom editions of the distro (I maintained 2 editions for EndeavourOS. Recently discontinued them because I'm exploring other things in life)
  - bonus: try to write a CI/CD pipeline for building the ISO (again, I did this for EndeavourOS and now we can have nightly builds on GitHub actions)
- try maintaining some add-ons to the distro. eg. on Arch, [pacoloco](https://github.com/anatol/pacoloco) is a tool that caches packages on a local repo. I use this a lot when testing my Dockerfiles because it saves the build times (don't need to download packages again and again since they get cached)
- write guides or tutorials relevant to the distro (I initially did this for EndeavourOS when the maintainers were less)


Just never ever think you're not qualified enough. Keep trying, you get a hang of it. In 2022, I was contributing to KDE. It was initially really tough figuring out WHAT to do and WHERE to do. couple of weeks in, I could mentally predict the source of most bugs without looking at the code. So, the investment is totally worth it.

> Like i am scared that i will write bad code to some popular project and it might end up causing problem later

Whats the worst that can happen? They'll close your PR? Right? Don't be scared. Go ahead and work in collaboration. In open source, communication is often more important than coding itself. And what if your buggy code is in fact merged? Regressions happen in softwares all the time. Even the Linux kernel regularly faces regressions, where a code addition broke existing features. Thats nothing to be afraid of.

<hr>

> so i am thinking of contributing to hyprland codebase cuz the main creator is kinda tired like burn outs so he wants ppl help and i use hyprland sometimes and i really like it so i think i will help with that

Hyprland is great! I was testing out a build of EndeavourOS with Hyprland default last evening. But well, I'm an i3wm user for half a decade now. I feel comfortable with i3wm, don't feel like switching :sweat_smile:

<hr>

I never thought I'll be giving raw advice on a spam repo, but here we are :joy: Feel free to drop a reply if you wanna ask something. I'm all ears.

image

**Comment by flyingcakes85** [comment]
> This really sucks our(indian) education system is raising employees like we kill creativity and interest of students and all they can think of is money and getting a job

During covid, I met (on the internet) an american paramedic who liked to rice his system. He was a medical guy by the day, but used to get technical help from me during free time. He ain't gonna earn anything from that. Did that just because he liked tech and ricing was a creative expression. There was also this european guy who works at a laptop repair shop. By the night, he developed his ARM linux distribution which he used.

There's lots of examples and the kind of people I've met who have deep genuine interest in software baffled me. Growing up in India, the only goals we were taught is that you gotta bag a high paying job, become CEO etc etc. And here I was, working with people who'll never earn a single penny from their code, but still, they code.

> i like to teach new ppl how to code and i also love linux so i teach them linux i like that when ppl are realy interested in coding

Same.

>  i am in 12th and i really really like computers so i want to pursue career in computer science but here comes jee cs is hardest branch to get because its a high paying field and ppl over saturated it

Good luck for your exams :+1: 

> in clg they study nothing at end they wanna get job so they see these bhaiya didi on yt teaching them coding (they themself are very at it) and promise them job so what students do they do this

As I mention on my blog, these bhaiya didi aren't educators. They're dream peddlers. Showing dreams to young students to lure them and then finally sell their courses.

I don't think anyone can fix it per se. On the contrary, I only found it easier to differentiate myself from the noise because of it. This is gonna be an unpopular opinion - but when everyone around you is trashy, you can manage to win by just being average.

**Pull request closed without merging**
