### PR TITLE
my 100k remote job offer

### PR DESCRIPTION
**Pull request by anuragts**
**This is a joke**

### CODE REVIEW

**Review by flyingcakes85 — APPROVED** [review]
You'll get remote job offer. Approved.

image

**Comment by anuragts** [comment]
Thanks ser, wen joining

**Comment by flyingcakes85** [comment]
Buy us $1000 Google Play gift card and then we give u job

**Comment by flyingcakes85** [comment]
I literally remember the episode from where that grab is taken 🤣

**Review by flyingcakes85 — APPROVED** [review]

**Comment by anuragts** [comment]
> I literally remember the episode from where that grab is taken 🤣

which episode ??

**Comment by flyingcakes85** [comment]
How do I find it lol it's in my head

**Pull request closed without merging**
